import { Types } from 'mongoose';
import { BackendStack, detectLanguage, FileEntryType, FrontendStack } from 'shared';
import { ProjectFileModel } from '../../models';
import { getBaseName, getParentPath } from '../files/file-validation.service';
import { expressTemplate } from './templates/express.template';
import { nextjsTemplate } from './templates/nextjs.template';
import { nodeTemplate } from './templates/node.template';
import { reactTemplate } from './templates/react.template';
import { vueTemplate } from './templates/vue.template';

export interface StarterEntry {
  path: string;
  type: FileEntryType;
  content?: string;
}

const COMMON_ENTRIES: StarterEntry[] = [
  {
    path: 'README.md',
    type: FileEntryType.FILE,
    content: '# New Project\n\nGenerated by Mingo AI. Start building in the workspace.\n',
  },
  {
    path: '.env.example',
    type: FileEntryType.FILE,
    content: '# Add your environment variables here\n',
  },
  { path: 'public', type: FileEntryType.FOLDER },
];

interface PackageJsonContribution {
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
  scripts?: Record<string, string>;
}

/** `npm run dev`/`build`/`start` need real scripts and real installable dependencies to mean
 *  anything in the sandbox terminal — an empty `scripts: {}` (the old behavior) meant every
 *  freshly-created project failed on the very first command a user tried. One contribution per
 *  chosen frontend/backend stack, merged into a single package.json (spec §15/§16). */
function frontendPackageContribution(frontend: FrontendStack): PackageJsonContribution {
  switch (frontend) {
    case FrontendStack.NEXTJS:
      return {
        dependencies: { next: '^15.5.22', react: '19.2.8', 'react-dom': '19.2.8' },
        devDependencies: { typescript: '^5.9.3', '@types/react': '^19.2.18', '@types/node': '^22.20.1' },
        scripts: { dev: 'next dev', build: 'next build', start: 'next start' },
      };
    case FrontendStack.VUE:
      return {
        dependencies: { vue: '^3.5.13' },
        devDependencies: { vite: '^6.3.5', '@vitejs/plugin-vue': '^5.2.1' },
        scripts: { dev: 'vite', build: 'vite build', preview: 'vite preview' },
      };
    case FrontendStack.REACT:
    default:
      return {
        dependencies: { react: '19.2.8', 'react-dom': '19.2.8' },
        devDependencies: { vite: '^6.3.5', '@vitejs/plugin-react': '^4.3.4' },
        scripts: { dev: 'vite', build: 'vite build', preview: 'vite preview' },
      };
  }
}

function backendPackageContribution(backend: BackendStack): PackageJsonContribution {
  switch (backend) {
    case BackendStack.EXPRESS:
      return { dependencies: { express: '^4.22.2' }, scripts: { server: 'node server/index.js' } };
    case BackendStack.NODE:
      return { scripts: { server: 'node server/index.js' } };
    case BackendStack.NESTJS:
    default:
      return {};
  }
}

function buildPackageJsonEntry(frontend: FrontendStack, backend: BackendStack): StarterEntry {
  const front = frontendPackageContribution(frontend);
  const back = backendPackageContribution(backend);

  const packageJson = {
    name: 'mingo-project',
    version: '0.1.0',
    private: true,
    scripts: { ...front.scripts, ...back.scripts },
    dependencies: { ...front.dependencies, ...back.dependencies },
    devDependencies: { ...front.devDependencies, ...back.devDependencies },
  };

  return {
    path: 'package.json',
    type: FileEntryType.FILE,
    content: `${JSON.stringify(packageJson, null, 2)}\n`,
  };
}

/** Technology-aware frontend structure — one template per `FrontendStack` option (spec §15/§16). */
function frontendEntries(frontend: FrontendStack): StarterEntry[] {
  switch (frontend) {
    case FrontendStack.NEXTJS:
      return nextjsTemplate();
    case FrontendStack.VUE:
      return vueTemplate();
    case FrontendStack.REACT:
    default:
      return reactTemplate();
  }
}

/**
 * Technology-aware backend structure. NestJS has no template yet — like Vue/Angular/Django in the
 * spec's own "future phases" list, it's left for when that stack gets real backend scaffolding
 * rather than shipping an empty placeholder.
 */
function backendEntries(backend: BackendStack): StarterEntry[] {
  switch (backend) {
    case BackendStack.EXPRESS:
      return expressTemplate();
    case BackendStack.NODE:
      return nodeTemplate();
    case BackendStack.NESTJS:
    default:
      return [];
  }
}

/** Only creates a small starter workspace — never a complete application (spec §14). */
export async function createStarterFiles(
  project: Types.ObjectId,
  owner: Types.ObjectId,
  frontend: FrontendStack,
  backend: BackendStack
): Promise<void> {
  const entries = [
    ...COMMON_ENTRIES,
    buildPackageJsonEntry(frontend, backend),
    ...frontendEntries(frontend),
    ...backendEntries(backend),
  ];

  await ProjectFileModel.insertMany(
    entries.map((entry) => {
      const content = entry.content ?? '';
      return {
        project,
        owner,
        name: getBaseName(entry.path),
        path: entry.path,
        type: entry.type,
        content: entry.type === FileEntryType.FILE ? content : undefined,
        language: entry.type === FileEntryType.FILE ? detectLanguage(entry.path) : undefined,
        parentPath: getParentPath(entry.path),
        size: entry.type === FileEntryType.FILE ? Buffer.byteLength(content, 'utf8') : 0,
        version: 1,
      };
    })
  );
}
