import { Types } from 'mongoose';
import { BackendStack, detectLanguage, FileEntryType, FrontendStack } from 'shared';
import { ProjectFileModel } from '../../models';
import { getBaseName, getParentPath } from '../files/file-validation.service';
import { expressTemplate } from './templates/express.template';
import { nextjsTemplate } from './templates/nextjs.template';
import { nodeTemplate } from './templates/node.template';
import { reactTemplate } from './templates/react.template';
import { vueTemplate } from './templates/vue.template';

export interface StarterEntry {
  path: string;
  type: FileEntryType;
  content?: string;
}

const COMMON_ENTRIES: StarterEntry[] = [
  {
    path: 'README.md',
    type: FileEntryType.FILE,
    content: '# New Project\n\nGenerated by Mingo AI. Start building in the workspace.\n',
  },
  {
    path: '.env.example',
    type: FileEntryType.FILE,
    content: '# Add your environment variables here\n',
  },
  {
    path: 'package.json',
    type: FileEntryType.FILE,
    content: `${JSON.stringify({ name: 'mingo-project', version: '0.1.0', private: true, scripts: {} }, null, 2)}\n`,
  },
  { path: 'public', type: FileEntryType.FOLDER },
];

/** Technology-aware frontend structure — one template per `FrontendStack` option (spec §15/§16). */
function frontendEntries(frontend: FrontendStack): StarterEntry[] {
  switch (frontend) {
    case FrontendStack.NEXTJS:
      return nextjsTemplate();
    case FrontendStack.VUE:
      return vueTemplate();
    case FrontendStack.REACT:
    default:
      return reactTemplate();
  }
}

/**
 * Technology-aware backend structure. NestJS has no template yet — like Vue/Angular/Django in the
 * spec's own "future phases" list, it's left for when that stack gets real backend scaffolding
 * rather than shipping an empty placeholder.
 */
function backendEntries(backend: BackendStack): StarterEntry[] {
  switch (backend) {
    case BackendStack.EXPRESS:
      return expressTemplate();
    case BackendStack.NODE:
      return nodeTemplate();
    case BackendStack.NESTJS:
    default:
      return [];
  }
}

/** Only creates a small starter workspace — never a complete application (spec §14). */
export async function createStarterFiles(
  project: Types.ObjectId,
  owner: Types.ObjectId,
  frontend: FrontendStack,
  backend: BackendStack
): Promise<void> {
  const entries = [...COMMON_ENTRIES, ...frontendEntries(frontend), ...backendEntries(backend)];

  await ProjectFileModel.insertMany(
    entries.map((entry) => {
      const content = entry.content ?? '';
      return {
        project,
        owner,
        name: getBaseName(entry.path),
        path: entry.path,
        type: entry.type,
        content: entry.type === FileEntryType.FILE ? content : undefined,
        language: entry.type === FileEntryType.FILE ? detectLanguage(entry.path) : undefined,
        parentPath: getParentPath(entry.path),
        size: entry.type === FileEntryType.FILE ? Buffer.byteLength(content, 'utf8') : 0,
        version: 1,
      };
    })
  );
}
