import {
  Archive,
  Building2,
  CheckCircle2,
  Copy,
  FolderPlus,
  KeyRound,
  Pencil,
  Rocket,
  RotateCcw,
  Trash2,
  UserCog,
  XCircle,
  Zap,
  ZapOff,
  type LucideIcon,
} from 'lucide-react';
import { ActivityType } from 'shared';

export const ACTIVITY_ICONS: Record<ActivityType, LucideIcon> = {
  [ActivityType.PROJECT_CREATED]: FolderPlus,
  [ActivityType.PROJECT_UPDATED]: Pencil,
  [ActivityType.PROJECT_DELETED]: Trash2,
  [ActivityType.PROJECT_ARCHIVED]: Archive,
  [ActivityType.PROJECT_DUPLICATED]: Copy,
  [ActivityType.DEPLOYMENT_TRIGGERED]: Rocket,
  [ActivityType.DEPLOYMENT_SUCCEEDED]: CheckCircle2,
  [ActivityType.DEPLOYMENT_FAILED]: XCircle,
  [ActivityType.DEPLOYMENT_ROLLED_BACK]: RotateCcw,
  [ActivityType.ENV_VAR_CREATED]: KeyRound,
  [ActivityType.ENV_VAR_UPDATED]: KeyRound,
  [ActivityType.ENV_VAR_DELETED]: KeyRound,
  [ActivityType.AUTO_DEPLOY_ENABLED]: Zap,
  [ActivityType.AUTO_DEPLOY_DISABLED]: ZapOff,
  [ActivityType.PRODUCTION_DEPLOY_APPROVED]: Rocket,
  [ActivityType.PROFILE_UPDATED]: UserCog,
  [ActivityType.WORKSPACE_CREATED]: Building2,
};
