import { randomUUID } from 'node:crypto';
import { mkdir, mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { Types } from 'mongoose';
import { FileEntryType } from 'shared';
import { ApiError } from '../../utils/ApiError';
import { logger } from '../../utils/logger';
import * as fileTreeService from '../files/file-tree.service';
import * as vfs from '../workspace/virtual-file-system.service';
import { isForbiddenPath } from './sandbox.security';
import { MaterializedWorkspace } from './sandbox.types';

/** Reject rather than silently truncate an oversized project (spec §2) — a partial test run that
 *  looks complete but silently dropped files would be worse than a clear error. */
const MAX_MATERIALIZED_BYTES = 50 * 1024 * 1024;

type FileTreeNode = Awaited<ReturnType<typeof fileTreeService.getFileTree>>[number];

function flattenFilePaths(nodes: FileTreeNode[], acc: string[] = []): string[] {
  for (const node of nodes) {
    if (node.type === FileEntryType.FILE) {
      acc.push(node.path);
    }
    if (node.children?.length) {
      flattenFilePaths(node.children as FileTreeNode[], acc);
    }
  }
  return acc;
}

/**
 * Walks the Phase 4 Virtual Filesystem (Mongo-backed, not a real disk) and writes every non-forbidden
 * file into a fresh, unique OS temp directory — the one place in this codebase a project's files ever
 * touch a real filesystem. The caller MUST call the returned `cleanup()` in a `finally`, even on
 * timeout/cancel/crash, so nothing generated by a test run (or the materialized source itself)
 * lingers on the host after the run ends.
 */
export async function materializeWorkspace(
  owner: Types.ObjectId,
  projectId: string
): Promise<MaterializedWorkspace> {
  const tree = await fileTreeService.getFileTree(owner, projectId);
  const paths = flattenFilePaths(tree).filter((filePath) => !isForbiddenPath(filePath));

  const dir = await mkdtemp(path.join(tmpdir(), 'mingo-test-'));
  const cleanup = async () => {
    await rm(dir, { recursive: true, force: true }).catch((err) => {
      logger.error('sandbox.materializer.cleanup_failed', {
        dir,
        error: err instanceof Error ? err.message : err,
      });
    });
  };

  let totalBytes = 0;
  let fileCount = 0;

  try {
    for (const filePath of paths) {
      const file = await vfs.readFile(owner, projectId, filePath).catch(() => null);
      if (!file) continue;

      const content = file.content ?? '';
      totalBytes += Buffer.byteLength(content, 'utf8');
      if (totalBytes > MAX_MATERIALIZED_BYTES) {
        throw ApiError.badRequest(
          `Project is too large to run tests in the sandbox (exceeds ${Math.floor(MAX_MATERIALIZED_BYTES / (1024 * 1024))}MB).`
        );
      }

      const destination = path.join(dir, filePath);
      const resolvedDestination = path.resolve(destination);
      if (!resolvedDestination.startsWith(path.resolve(dir))) {
        // Defense in depth — every path here already passed `assertSafePath` when it was written to
        // the virtual filesystem, so this should never trigger.
        continue;
      }

      await mkdir(path.dirname(destination), { recursive: true });
      await writeFile(destination, content, 'utf8');
      fileCount += 1;
    }
  } catch (err) {
    await cleanup();
    throw err;
  }

  if (fileCount === 0) {
    await cleanup();
    throw ApiError.badRequest('This project has no files to test yet.');
  }

  return { dir, fileCount, cleanup };
}

/** Used by callers that want a unique scratch path outside the materialized workspace (e.g. a JSON
 *  test-reporter output file) without polluting the project's own directory tree. */
export function scratchFilePath(suffix: string): string {
  return path.join(tmpdir(), `mingo-test-${randomUUID()}${suffix}`);
}
