import { Types } from 'mongoose';
import { detectLanguage, FileEntryType, FrontendStack } from 'shared';
import { ProjectFileModel } from '../../models';
import { getBaseName, getParentPath } from './file-validation.service';

interface StarterEntry {
  path: string;
  type: FileEntryType;
  content?: string;
}

const COMMON_ENTRIES: StarterEntry[] = [
  {
    path: 'README.md',
    type: FileEntryType.FILE,
    content: '# New Project\n\nGenerated by Mingo AI. Start building in the workspace.\n',
  },
  {
    path: '.env.example',
    type: FileEntryType.FILE,
    content: '# Add your environment variables here\n',
  },
  {
    path: 'package.json',
    type: FileEntryType.FILE,
    content: `${JSON.stringify({ name: 'mingo-project', version: '0.1.0', private: true, scripts: {} }, null, 2)}\n`,
  },
  { path: 'public', type: FileEntryType.FOLDER },
];

function nextjsEntries(): StarterEntry[] {
  return [
    { path: 'app', type: FileEntryType.FOLDER },
    {
      path: 'app/layout.tsx',
      type: FileEntryType.FILE,
      content:
        "export default function RootLayout({ children }: { children: React.ReactNode }) {\n  return (\n    <html lang=\"en\">\n      <body>{children}</body>\n    </html>\n  );\n}\n",
    },
    {
      path: 'app/page.tsx',
      type: FileEntryType.FILE,
      content:
        'export default function Page() {\n  return <main>Welcome to your new Mingo AI project.</main>;\n}\n',
    },
  ];
}

function vueEntries(): StarterEntry[] {
  return [
    { path: 'src', type: FileEntryType.FOLDER },
    { path: 'src/components', type: FileEntryType.FOLDER },
    {
      path: 'src/main.js',
      type: FileEntryType.FILE,
      content: "import { createApp } from 'vue';\nimport App from './App.vue';\n\ncreateApp(App).mount('#app');\n",
    },
    {
      path: 'src/App.vue',
      type: FileEntryType.FILE,
      content:
        '<template>\n  <div>Welcome to your new Mingo AI project.</div>\n</template>\n\n<script setup>\n</script>\n',
    },
  ];
}

function reactEntries(): StarterEntry[] {
  return [
    { path: 'src', type: FileEntryType.FOLDER },
    { path: 'src/components', type: FileEntryType.FOLDER },
    {
      path: 'src/main.jsx',
      type: FileEntryType.FILE,
      content:
        "import React from 'react';\nimport ReactDOM from 'react-dom/client';\nimport App from './App';\n\nReactDOM.createRoot(document.getElementById('root')).render(\n  <React.StrictMode>\n    <App />\n  </React.StrictMode>\n);\n",
    },
    {
      path: 'src/App.jsx',
      type: FileEntryType.FILE,
      content: "export default function App() {\n  return <div>Welcome to your new Mingo AI project.</div>;\n}\n",
    },
  ];
}

function buildStarterEntries(frontend: FrontendStack): StarterEntry[] {
  switch (frontend) {
    case FrontendStack.NEXTJS:
      return [...COMMON_ENTRIES, ...nextjsEntries()];
    case FrontendStack.VUE:
      return [...COMMON_ENTRIES, ...vueEntries()];
    case FrontendStack.REACT:
    default:
      return [...COMMON_ENTRIES, ...reactEntries()];
  }
}

/** Only creates a small starter workspace — never a complete application (spec section 30). */
export async function createStarterFiles(
  project: Types.ObjectId,
  owner: Types.ObjectId,
  frontend: FrontendStack
): Promise<void> {
  const entries = buildStarterEntries(frontend);

  await ProjectFileModel.insertMany(
    entries.map((entry) => {
      const content = entry.content ?? '';
      return {
        project,
        owner,
        name: getBaseName(entry.path),
        path: entry.path,
        type: entry.type,
        content: entry.type === FileEntryType.FILE ? content : undefined,
        language: entry.type === FileEntryType.FILE ? detectLanguage(entry.path) : undefined,
        parentPath: getParentPath(entry.path),
        size: entry.type === FileEntryType.FILE ? Buffer.byteLength(content, 'utf8') : 0,
        version: 1,
      };
    })
  );
}
